"""empty message

Revision ID: 1aa5e9e0334c
Revises: a8626a04526a
Create Date: 2024-12-09 05:26:49.310965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa5e9e0334c'
down_revision = 'a8626a04526a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
