"""empty message

Revision ID: c3e65428871a
Revises: 8c3ae3af51c7
Create Date: 2024-12-04 19:57:55.770158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e65428871a'
down_revision = '8c3ae3af51c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.drop_column('place_name')

    # ### end Alembic commands ###
